# Generated by Django 5.2 on 2025-05-06 20:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_handler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
