# Generated by Django 5.2 on 2025-05-10 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_handler', '0002_video_date_uploaded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
